function [fitresult, gof] = twoDgaussian_tiptiltfit(tips, tilts, all_pks)
%CREATEFIT(TIPS,TILTS,ALL_PKS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tips
%      Y Input : tilts
%      Z Output: all_pks
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Jul-2021 11:21:57


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( tips, tilts, all_pks );

% Set up fittype and options.
ft = fittype( 'A*exp(-((x-x0).^2/(2*sigx.^2) + (y-y0).^2/(2*sigy.^2)));', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1 50 50 0 0];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'all_pks vs. tips, tilts', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'tips', 'Interpreter', 'none' );
% ylabel( 'tilts', 'Interpreter', 'none' );
% zlabel( 'all_pks', 'Interpreter', 'none' );
% grid on


